name: connexa
description: A starting point for Dart libraries or applications.
version: 0.0.1
author: Gil Mendes <gilmendes@designture.net>
homepage: https://www.designture.net/connexa

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  logging: any
  events: any
  route: any
  uuid: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
